### ISSUE TITLE
facexlib without CUDA

### ISSUE THREAD

**Issue by nihirv** [xinntao/facexlib#5]
Hey,

I'm using this because I'm interested in testing out the GFPGAN repo. However I'd like to run this on a CPU version of torch only. Since we're performing inference and not training, would you be able to support this?

Thanks for the fantastic work though btw :)

**Comment by nihirv** [comment]
Hmm, I made the change in `utils/face_restoration_helper.py > FaceRestoreHelper > __init__`, and was planning on opening a pr, but it seems that the `basicsr` library needs CUDA drivers too. Still, it's only a one line change and those who want to use `facexlib` without GPU might benefit from it, so I'll open a pr

**Comment by xinntao** [comment]
1. The current GFPGAN requires GPU, so it may not available for CPU inference. We may add a CPU-support model later.
2. I think BasicSR can support CPU only. (if we do not use those cuda extensions.)
3. Thanks, it is better to add an option for supporting CPU

**Comment by nihirv** [comment]
1. Yes please - that'd be great. Is it the StyleGAN part which needs the GPU?
2. I'm getting a: "OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root." through `basicsr\ops\dcn\deform_conv.py", line 14` inside the `if BASICSR_JIT == 'True':` flag
3. PR opened (it's not a flag, just a device check): https://github.com/xinntao/facexlib/pull/6

**Comment by xinntao** [comment]
@nihirv 
1. The StyleGAN needs customized CUDA(with GPU) extensions. So the original model requires GPU.  I have updated a new version which does not require such CUDA extensions. So the GFPGAN can be run with CPU/ or run on windows.  See the updates in : https://github.com/TencentARC/GFPGAN
2. I have merged the PR.  Thanks.  :-)
